name: CI
on: push

jobs:
  build:
    if: contains(github.event.head_commit.message, 'publish')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Flutter action
        uses: subosito/flutter-action@v2.7.1
        with:
          flutter-version: 3.3.4
      - run: flutter pub get
      - run: flutter build apk --split-per-abi

      - uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-shanghai.aliyuncs.com
          access-key-id: ${{ secrets.ACCESSKEYID }}
          access-key-secret: ${{ secrets.ACCESSKEYSECRET }}
      - run: ossutil cp -rf ./build/app/outputs/apk/release/jieapp.apk oss://luhaojie/apks/

      - name: Send success message
        if: success()
        run: |
          curl -G "https://wss.laihaojie.com/api/tools/releaseSuccess" --data-urlencode "id=阿杰的APP"
          curl -X GET "https://api.laihaojie.com/api/public/updateAndroidVersion"

      - name: Send failed message
        if: failure()
        run: curl -G "https://wss.laihaojie.com/api/tools/releaseFailed" --data-urlencode "id=阿杰的APP"
